### ISSUE TITLE
Mention the relationship with the Geolocation API

### ISSUE THREAD

**Issue by xfq** [w3c/geolocation-sensor#33]
As the subject line says, we should mention the relationship with the Geolocation API (e.g., coexist with or intend to deprecate the Geolocation API) in the Status of this document section.

**Comment by anssiko** [comment]
I think coexists is a reasonable expectation given the widespread usage of the Geolocation API.

PR #35 is the first proposal. 

PTAL @xfq @tomayac @mkruisselbrink

**Comment by mkruisselbrink** [comment]
Seems reasonable to me, yes.
