### ISSUE TITLE
Some news ?

### ISSUE THREAD

**Issue by jzijp38** [w3c/geolocation-sensor#54]
We are in 2023, no news here for more than one year. This project is still alive?
I can not understand why this asked functionality is not deployed.
Privacy?what difference with native apps? Browser con block this by default as the do with notification.

A lot of minor functionalities are discuted, this major no.

Then?

**Comment by tomayac** [comment]
I think it’s fair to say that due to a number of reasons, like shifted priorities and privacy challenges, this project is currently on-hold. If you have use cases, please consider sharing them, so they are ready when work on this is being picked up again.
