### ISSUE TITLE
Investigate high accuracy mode alternatives

### ISSUE THREAD

**Issue by anssiko** [w3c/geolocation-sensor#6]
The [`highAccuracy`][1] flag is a hint, and as a consequence, has known interop issues. Investigate whether this flag could be dropped from the modernized API. Are there any use cases that would support porting it over?

It seems a better alternative would be an API that addresses the following use case properly, especially for a one-shot geolocation request (via https://github.com/WICG/geolocation-sensor/issues/2):

> return me a position as soon as the accuracy is within Z meters. 

This suggest a web developer settable accuracy thresholds of some sort.

[1]: https://www.w3.org/TR/geolocation-API/#high-accuracy

**Comment by yellowdoge** [comment]
Re. part 1, UAs had quite the latitude in implementing the previous Geolocation API, resulting in a soup of sensors including WiFi and GPS, with a potential low accuracy IP mapping as a fallback. Developers tended to resent the lack of feedback as to what choices were being done without proper communication, so perhaps we could consider a list of supported/active providers of geolocation like Android [seems to have](https://developer.android.com/guide/topics/location/strategies.html). 

Use case two reminds me a bit of Geofencing of which there was an API that seems to [be put on ice](https://www.w3.org/TR/geofencing/), @mkruisselbrink might be able to provide some insights.

**Comment by martijnthe** [comment]
For our use cases it's desirable to be able to let the client of the `GeolocationSensor` specify "desired accuracy" (in meters), to enable the "sensor backend" to balance low power consumption and the needs of the sensor clients.

I think it's best to let the client express the accuracy in absolute terms (meters) rather than a relative concept like "high accuracy".

This is related to, but different from, https://github.com/WICG/geolocation-sensor/issues/13

**Comment by alexshalamov** [comment]
@anssiko If I remember correctly, we were experimenting with `threshold` parameter in the options that was meant to be used for such use cases. The specification already defines [such concept](https://w3c.github.io/sensors/#reading-change-threshold), however, it is not controllable from the client side.

@pozdnyakov WDYT?

**Comment by pozdnyakov** [comment]
`threshold` could be provided either as a part of the generic `SensorOptions` construction parameters or specifically for the `GeolocationSensor` class. Note, that `threshold` parameter can only set the minimum value for threshold, the actual threshold might be bigger (depending on the actual device sensor and the underlying software platform)

**Comment by martijnthe** [comment]
Having both a `threshold` (meters) and `desiredAccuracy` (meters) in the constructor parameters object makes sense to me.

**Comment by anssiko** [comment]
This issue seems to be a duplicate of #13.

I submitted a proposal in https://github.com/WICG/geolocation-sensor/issues/13#issuecomment-366701610 and suggest we continue discussion in that issue.

**Comment by tomayac** [comment]
> This issue seems to be a duplicate of #13.

…which in turn IMHO can be merged into https://github.com/w3c/geolocation-sensor/issues/25. Are you OK with that?

**Comment by anssiko** [comment]
There seems not to be good use cases for `highAccuracy` bit, also implementation experience from Geolocation API demonstrated interop was hard. Better abstractions to explore as alternatives are [accuracy](https://github.com/w3c/geolocation-sensor/issues?q=is%3Aissue+is%3Aopen+label%3Ageo-accuracy) and [latency](https://github.com/w3c/geolocation-sensor/issues?q=is%3Aissue+is%3Aopen+label%3Ageo-latency).
